sudo: required
services:
  - docker

before_install:
  - docker build -t imkalirajan/docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true imkalirajan/docker-multi npm run test

after_success:
  - docker build -t imkalirajan/multi-client ./client
  - docker build -t imkalirajan/multi-nginx ./nginx
  - docker build -t imkalirajan/multi-server ./server
  - docker build -t imkalirajan/multi-worker ./worker

  # Login in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images to docker hub
  - docker push imkalirajan/multi-client
  - docker push imkalirajan/multi-nginx
  - docker push imkalirajan/multi-server
  - docker push imkalirajan/multi-worker
